### ISSUE TITLE
the example doesn't work

### ISSUE THREAD

**Issue by hadycodes** [alb423/FFmpegAudioPlayer#1]
this project doesn't work

**Comment by alb423** [comment]
I change the flag DECODE_AUDIO_BY_FFMPEG to true.
It should work now. 
Please try again.

**Comment by hadycodes** [comment]
thank you
i w'll try it now

**Comment by hadycodes** [comment]
it's work now thank you very much +1,+1,+1,+1,+1,+1,+1,+1,+1
