### ISSUE TITLE
Record proplem

### ISSUE THREAD

**Issue by hadycodes** [alb423/FFmpegAudioPlayer#3]
sorry but there is error when i tap on record putton 
![screen shot 2014-02-13 at 10 38 30 am](https://f.cloud.github.com/assets/3501824/2157963/44a903d8-948a-11e3-92dd-b3dc9589d0df.png)

**Comment by alb423** [comment]
The problem may be the incorrect file path.
I change the file path from my local path to [NSBundle mainBundle]. It should be fine now.

BTW, the recording function is not finished yet. 
It just can record when the audio is playing. 
The usage I expected is 
1. press play to play audio
2. press record to start record
3. press record to stop record
4. press play to stop audio.

**Comment by hadycodes** [comment]
thanks
